= Waste Data Tool

This repository contains the source code and usage instructions for the Waste Data Tool (*WDT*).
The WDT provides functionality for:

* reading open data about waste in Scotland
* _re-working_ this data so that it is *easier* to use, understand, consume & parse
* writing the re-worked data as simple CSV and JSON files, to a single public repository.

The WDT is an output of the
https://www.stir.ac.uk/research/hub/contract/933675[Data Commons Scotland]
research project.

WARNING: This is software is very rough'n'ready - it is at a proof-of-concept level.

NOTE: Information about the mothballed Wikibase feature, can be found link:doc/wikibase.adoc[here].

---

== Use

=== Setting up the tools, environment, etc.

Prerequisite software:

* Git 2.24.0 (_-ish_)
* JDK 11.0.5 (_-ish_)
* Clojure 1.10.1 (_-ish_)
* Cojure Tools 1.10.1.754 (_-ish_)

=== Get the software

[source]
----
C:\>git clone https://github.com/data-commons-scotland/dcs-wdt.git
Cloning into 'dcs-wdt'...
remote: Enumerating objects: 333, done.
remote: Counting objects: 100% (333/333), done.
remote: Compressing objects: 100% (165/165), done.
Receiving objects:  87% (290/333)used 270 (delta 112), pack-reused 0R
Receiving objects: 100% (333/333), 63.10 KiB | 897.00 KiB/s, done.
Resolving deltas: 100% (175/175), done.
----

=== Run

Create ingestable local files from SPARQL queries:

[source]
----
clj -X:csv
----

Create a database from ingestable local files then describe the database on the console:

[source]
----
clj -X:db
----

Create a database from ingestable local files then generate CSV & JSON files for general use:

[source]
----
clj -X:general
----
