= Waste Data Tool

This repository contains the source code and usage instructions for the Waste Data Tool (*WDT*).
The WDT provides functionality for:

* reading open data about waste in Scotland
* _re-working_ this data so that it is *easier* to use, understand, consume & parse
* writing the re-worked data as simple CSV and JSON files, to a single public repository.

The WDT is an output of the
https://www.stir.ac.uk/research/hub/contract/933675[Data Commons Scotland]
research project.

WARNING: This is software is very rough'n'ready - it is at a proof-of-concept level.

NOTE: Information about the mothballed Wikibase feature, can be found link:doc/wikibase.adoc[here].

---

== Use

=== Setting up the tools, environment, etc.

Prerequisite software:

* Git 2.24.0 (_-ish_)
* JDK 11.0.5 (_-ish_)
* Clojure 1.10.1 (_-ish_)
* Cojure Tools 1.10.1.754 (_-ish_)
 
* `lib/csvw-validator-cli-app-1.0.0-SNAPSHOT.jar` (performs extra CSVW related validation; used by `gen-turtle`; get from https://github.com/malyvoj3/csvw-validator[Vojtech's repo])
* `lib/csv2rdf-0.4.7-SNAPSHOT-standalone.jar` (performs the actual Turtle generation; used by `gen-turtle`; get from https://github.com/Swirrl/csv2rdf[Swirrl's repo]) 
* `lib/blazegraph.jar` 2.1.6 (_ish_) (provides an RDF store and a SPARQL service; used by `run-blaze`; get from https://github.com/blazegraph/database[Blazegraph's repo])

=== Get the software

[source]
----
C:\>git clone https://github.com/data-commons-scotland/dcs-wdt.git
----

=== Run

Create ingestable local files from SPARQL queries:

[source]
----
clj -X:sparql
----

Create a database from ingestable local files then describe the database on the console:

[source]
----
clj -X:db
----

Create a database from ingestable local files then generate CSV & JSON files for general use:

[source]
----
clj -X:general
----

Validate the generated CSV files against their CSVW specifications, then generate their equivalent Turtle files: 

[source]
----
gen-turtle
----

Create ZIP bundles of the CSV, JSON, Turtle & CSVW files: 

[source]
----
zip-files
----

Load the generated Turtle files into a Blazegraph DB file, and then run a Blazegraph service: 

[source]
----
run-blaze
----