(ns dcs.wdt.ingest.meta)

(def internal
  {:region                                {:description  "Scottish council areas with UK government codes and Wikidata IDs."
                                           :creator      "DCS"
                                           :created-when 2021
                                           :supplier     "DCS"
                                           :supply-url   "file:///"
                                           :licence      "CC BY 4.0"
                                           :licence-url  "https://creativecommons.org/licenses/by/4.0/"
                                           :notes        "Choose to use the common name for each region."}
   :household-waste                       {:description  "The categorised quantities of the ('managed') waste generated by household."
                                           :creator      "SEPA"
                                           :created-when 2020
                                           :supplier     "statistics.gov.scot"
                                           :supply-url   "http://statistics.gov.scot/data/household-waste"
                                           :licence      "OGL v3.0"
                                           :licence-url  "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
                                           :notes        "Published as an RDF data cube, the data can be accessed via SPARQL."}
   :household-co2e                        {:description  "The carbon impact of the waste generated by household."
                                           :creator      "SEPA"
                                           :created-when 2020
                                           :supplier     "SEPA"
                                           :supply-url   "https://www.environment.gov.scot/data/data-analysis/household-waste"
                                           :licence      "OGL v2.0"
                                           :licence-url  "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/"
                                           :notes        "Published through a web-based data tool, the data can be downloaded as a CSV file."}
   :business-waste-by-region              {:description  "The categorised quantities of the waste generated by industry & commerce."
                                           :creator      "SEPA"
                                           :created-when 2020
                                           :supplier     "SEPA"
                                           :supply-url   "https://www.sepa.org.uk/environment/waste/waste-data/waste-data-reporting/business-waste-data"
                                           :licence      "OGL v2.0"
                                           :licence-url  "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/"
                                           :notes        "Published as a series of downloadable Excel files."}
   :business-waste-by-sector              {:description  "The categorised quantities of the waste generated by industry & commerce."
                                           :creator      "SEPA"
                                           :created-when 2020
                                           :supplier     "SEPA"
                                           :supply-url   "https://www.sepa.org.uk/environment/waste/waste-data/waste-data-reporting/business-waste-data"
                                           :licence      "OGL v2.0"
                                           :licence-url  "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/"
                                           :notes        "Published as a series of downloadable Excel files."}
   :waste-site-io                         {:description  "The locations, services, capacities and per-year I/O of waste sites."
                                           :creator      "SEPA"
                                           :created-when 2020
                                           :supplier     "SEPA"
                                           :supply-url   "https://www.sepa.org.uk/data-visualisation/waste-sites-and-capacity-tool"
                                           :licence      "OGL v2.0"
                                           :licence-url  "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/"
                                           :notes        "Published through a web-based data tool, the data can be downloaded as a CSV file."}
   :waste-site-material-io                {:description  "The per-year per-material I/O of waste sites."
                                           :creator      "SEPA"
                                           :created-when 2020
                                           :supplier     "SEPA"
                                           :supply-url   "https://www.sepa.org.uk/data-visualisation/waste-sites-and-capacity-tool"
                                           :licence      "OGL v2.0"
                                           :licence-url  "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/"
                                           :notes        "Published through a web-based data tool, the data can be downloaded as a CSV file."}
   :bin-collection                        {:description  "The categorised quantities of the waste collected from household bins."
                                           :creator      "Stirling council"
                                           :created-when 2021
                                           :supplier     "Stirling council"
                                           :supply-url   "https://data.stirling.gov.uk/dataset/waste-management"
                                           :licence      "OGL v3.0"
                                           :licence-url  "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
                                           :notes        "Published through a web-based data tool (CKAN), the data can be downloaded as CSV files."}
   :sepa-material                         {:description  "SEPA's waste materials classification."
                                           :creator      "SEPA"
                                           :created-when 2020
                                           :supplier     "SEPA"
                                           :supply-url   "https://www.sepa.org.uk/data-visualisation/waste-sites-and-capacity-tool"
                                           :licence      "OGL v2.0"
                                           :licence-url  "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/"
                                           :notes        "Published through a web-based data tool, the data can be downloaded as CSV files."}
   :ewc-code                              {:description  "EWC (European Waste Classification) codes and descriptions. Also a mapping to SEPA's materials classification."
                                           :creator      "European Commission of the EU"
                                           :created-when 2000
                                           :supplier     "Publications Office of the EU"
                                           :supply-url   "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02000D0532-20150601&from=EN#tocId7"
                                           :licence      "CC BY 4.0"
                                           :licence-url  "https://creativecommons.org/licenses/by/4.0/"
                                           :notes        "Published as a web page."}
   :co2e-multiplier                       {:description  "Per-material weight-multipliers to calaculate CO2e amounts. This data has been copied from section 6.2 of The Scottish Carbon Metric."
                                           :creator      "ZWS"
                                           :created-when 2012
                                           :supplier     "ZWS"
                                           :supply-url   "https://www.zerowastescotland.org.uk/sites/default/files/The%20Scottish%20Carbon%20Metric.pdf"
                                           :licence      "OGL v3.0"
                                           :licence-url  "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
                                           :notes        "Published as a PDF document."}
   :household                             {:description  "Occupied residential dwelling counts. Useful for calculating per-household amounts."
                                           :creator      "NRS"
                                           :created-when 2020
                                           :supplier     "statistics.gov.scot"
                                           :supply-url   "http://statistics.gov.scot/data/household-estimates"
                                           :licence      "OGL v3.0"
                                           :licence-url  "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
                                           :notes        "Published as an RDF data cube, the data can be accessed via SPARQL."}
   :population                            {:description  "People counts. Useful for calculating per-citizen amounts."
                                           :creator      "NRS"
                                           :created-when 2021
                                           :supplier     "statistics.gov.scot"
                                           :supply-url   "http://statistics.gov.scot/data/population-estimates-current-geographic-boundaries"
                                           :licence      "OGL v3.0"
                                           :licence-url  "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
                                           :notes        "Published as an RDF data cube, the data can be accessed via SPARQL."}
   :fairshare                             {:description  "The per-year per-quarter per-material amount (weight and CO2e) of reused items."
                                           :creator      "The Fair Share"
                                           :created-when 2021
                                           :supplier     "The Fair Share"
                                           :supply-url   "file:///"
                                           :licence      "CC BY 4.0"
                                           :licence-url  "https://creativecommons.org/licenses/by/4.0/"
                                           :notes        "Supplied as an Excel spreadsheet."}
   :stirling-community-food-tonnes        {:description  "The per-day amount of food flowing in/out of the organisation from/to partner organisations." 
                                           :creator      "Transition Stirling"
                                           :created-when 2021
                                           :supplier     "Transition Stirling"
                                           :supply-url   "file:///"
                                           :licence      "CC BY 4.0"
                                           :licence-url  "https://creativecommons.org/licenses/by/4.0/"
                                           :notes        "Supplied as an Excel spreadsheet."}
   :stirling-community-food-footfall      {:description  "The per-day number of people visiting the store."
                                           :creator      "Transition Stirling"
                                           :created-when 2021
                                           :supplier     "Transition Stirling"
                                           :supply-url   "file:///"
                                           :licence      "CC BY 4.0"
                                           :licence-url  "https://creativecommons.org/licenses/by/4.0/"
                                           :notes        "Supplied as an Excel spreadsheet."}
   :ace-furniture-count                   {:description  "The per-accounting-period per-furniture-category counts of items sold."
                                           :creator      "Alloa Community Enterprises"
                                           :created-when 2021
                                           :supplier     "Alloa Community Enterprises"
                                           :supply-url   "file:///"
                                           :licence      "CC BY 4.0"
                                           :licence-url  "https://creativecommons.org/licenses/by/4.0/"
                                           :notes        "Supplied as an Excel spreadsheet."}
   :ace-furniture-avg-weight              {:description  "The per-furniture-category average weights of items sold."
                                           :creator      "Alloa Community Enterprises"
                                           :created-when 2021
                                           :supplier     "Alloa Community Enterprises"
                                           :supply-url   "file:///"
                                           :licence      "CC BY 4.0"
                                           :licence-url  "https://creativecommons.org/licenses/by/4.0/"
                                           :notes        "Supplied as an Excel spreadsheet."}
   :ace-furniture-to-scottishCarbonMetric {:description  "A per-furniture-category mapping to a Scottish Carbon Metric material."
                                           :creator      "DCS"
                                           :created-when 2021
                                           :supplier     "DCS"
                                           :supply-url   "file:///"
                                           :licence      "CC BY 4.0"
                                           :licence-url  "https://creativecommons.org/licenses/by/4.0/"
                                           :notes        "A reasoned mapping."}
   :household-waste-analysis              {:description  "(An anonymised subset of) An analysis of sampled bin collection contents."
                                           :creator      "ZWS"
                                           :created-when 2021
                                           :supplier     "ZWS"
                                           :supply-url   "file:///"
                                           :licence      "CC BY 4.0"
                                           :licence-url  "https://creativecommons.org/licenses/by/4.0/"
                                           :notes        "Supplied as an Excel spreadsheet."}
   :meta                                  {:description  "Meta level information."
                                           :creator      "DCS"
                                           :created-when 2021
                                           :supplier     "DCS"
                                           :supply-url   "file:///"
                                           :licence      "CC BY 4.0"
                                           :licence-url  "https://creativecommons.org/licenses/by/4.0/"
                                           :notes        ""}})


(defn db-from-internal
  []
  (map (fn [[k m]] (assoc m 
                          :record-type :meta
                          :name (name k)))
       internal))